from ..models import db
from ..models.product import Product
from datetime import datetime

def seed_products():
    """Populates the database with sample products."""
    products = [
         {
        'name': 'La Mer Crème de la Mer Moisturizing Cream',
        'brand': 'La Mer',
        'category': 'skincare',
        'subcategory': 'moisturizer',
        'description': 'The legendary moisturizing cream that transforms skin with the healing power of the sea. This luxurious formula helps renew skin for a firmer, more radiant appearance.',
        'price': 190.00,
        'amazon_url': 'https://amzn.to/3IQBRLA',
        'image_url': 'https://m.media-amazon.com/images/I/61dk40nyxqL._SL1000_.jpg', # Changed to /static/images/
        'rating': 4.5,
        'review_count': 1250,
        'ingredients': 'Sea Kelp Bioferment, Eucalyptus, Wheat Germ, Sunflower, Alfalfa',
        'benefits': 'Deeply moisturizes, improves skin texture, reduces fine lines, enhances radiance',
        'usage_instructions': 'Apply morning and evening to clean skin. Warm between fingertips before applying.',
        'is_featured': True
    },
    {
        'name': 'SK-II Facial Treatment Essence',
        'brand': 'SK-II',
        'category': 'skincare',
        'subcategory': 'essence',
        'description': 'The iconic essence that transforms skin with over 90% PITERA™, a bio-ingredient derived from yeast fermentation that resembles your skin\'s Natural Moisturizing Factors.',
        'price': 99.00,
        'amazon_url': 'https://amzn.to/4lf2qHN',
        'image_url': 'https://cdn11.bigcommerce.com/s-x3hur0xe4r/images/stencil/500w/products/151/2550/FTE_1_2__11815__27159.1753696929.jpg?c=1',
        'rating': 4.7,
        'review_count': 890,
        'ingredients': 'PITERA™, Butylene Glycol, Pentylene Glycol, Water',
        'benefits': 'Improves skin texture, enhances radiance, reduces appearance of spots, smooths fine lines',
        'usage_instructions': 'Apply after cleansing, before moisturizer. Pat gently into skin.',
        'is_featured': True
    },
    {
        'name': 'Charlotte Tilbury Pillow Talk Lipstick',
        'brand': 'Charlotte Tilbury',
        'category': 'makeup',
        'subcategory': 'lipstick',
        'description': 'The universally flattering nude-pink lipstick inspired by the pillow talk shade. This creamy, buildable formula delivers full coverage with a satin finish.',
        'price': 20.00,
        'amazon_url': 'https://amzn.to/4fpFnJ6',
        'image_url': 'https://thevault.pk/cdn/shop/files/CHARLOTTE_TILBURY_-_Matte_Revolution_Lipstick_-_Pillow_Talk_360x.png?v=1728135866',
        'rating': 4.6,
        'review_count': 2100,
        'ingredients': 'Castor Seed Oil, Candelilla Wax, Carnauba Wax, Vitamin E',
        'benefits': 'Long-lasting color, moisturizing formula, buildable coverage, universally flattering',
        'usage_instructions': 'Apply directly to lips or use a lip brush for precise application.',
        'is_featured': True
    },
    {
        'name': 'Tom Ford Black Orchid Eau de Parfum',
        'brand': 'Tom Ford',
        'category': 'fragrance',
        'subcategory': 'perfume',
        'description': 'A luxurious and sensual fragrance of rich, dark accords and an alluring potion of black orchids and spice. This iconic scent is both modern and timeless.',
        'price': 75.50,
        'amazon_url': 'https://amzn.to/4mtvAnE',
        'image_url': 'https://khayest.pk/cdn/shop/files/WhatsAppImage2024-03-07at17.35.53.webp?v=1728333734&width=416.jpg', # Changed to /static/images/
        'rating': 4.4,
        'review_count': 1580,
        'ingredients': 'Black Orchid, Spice, Dark Chocolate, Incense, Patchouli, Vanilla',
        'benefits': 'Long-lasting fragrance, sophisticated scent, versatile for day and night',
        'usage_instructions': 'Spray on pulse points: wrists, neck, and behind ears.',
        'is_featured': True
    },
    {
        'name': 'Estée Lauder Advanced Night Repair Serum',
        'brand': 'Estée Lauder',
        'category': 'skincare',
        'subcategory': 'serum',
        'description': 'The #1 anti-aging serum that helps reduce multiple signs of aging with powerful technology that activates skin\'s natural nighttime renewal.',
        'price': 16.00,
        'amazon_url': 'https://amzn.to/45tqlhT',
        'image_url': 'https://www.esteelauder.com/media/export/cms/products/640x640/el_sku_PG5001_640x640_0.jpg', # <-- **FIXED: Was '/images/' (empty), now points to a placeholder**
        'rating': 4.5,
        'review_count': 3200,
        'ingredients': 'ChronoluxCB™ Technology, Hyaluronic Acid, Bifida Ferment Lysate',
        'benefits': 'Reduces fine lines, improves skin texture, enhances radiance, strengthens skin barrier',
        'usage_instructions': 'Apply every night after cleansing and before moisturizer.',
        'is_featured': False
    },
    {
        'name': 'Dior Addict Lip Glow Oil',
        'brand': 'Dior',
        'category': 'makeup',
        'subcategory': 'lip-care',
        'description': 'A nourishing, glossy lip oil that reacts to the moisture level of your lips to reveal a custom color and shine that lasts for 6 hours.',
        'price': 5.00,
        'amazon_url': 'https://amzn.to/4lZhLxm',
        'image_url': 'https://www.sephora.com/productimages/sku/s2316172-main-zoom.jpg?imwidth=465', # Changed to /static/images/
        'rating': 4.3,
        'review_count': 1750,
        'ingredients': 'Cherry Oil, Jojoba Oil, Vitamin E, Color-Reviver Technology',
        'benefits': 'Nourishes lips, custom color reveal, long-lasting shine, comfortable wear',
        'usage_instructions': 'Apply generously to lips. Reapply as needed throughout the day.',
        'is_featured': False
    },
    {
    "name": "BIODANCE Bio-Collagen Real Deep Mask",
    "brand": "BIODANCE",
    "category": "skincare",
    "subcategory": "mask",
    "description": "A hydrating hydrogel mask infused with ultra-low molecular collagen that turns transparent as the skin absorbs the essence. It aims to improve skin elasticity, minimize the appearance of pores, and provide deep, long-lasting moisture.",
    "price": 19.00,
    "amazon_url": "https://amzn.to/4l60qRV",
    "image_url": "https://m.media-amazon.com/images/I/51299uVd3YL._SL1000_.jpg",
    "rating": 4.9,
    "review_count": 1750,
    "ingredients": "Water, Collagen Extract, Galactomyces Ferment Filtrate, Glycerin, Acrylates Copolymer, Niacinamide, Ceratonia Siliqua (Carob) Gum, Chondrus Crispus Extract, Betaine, Algin, Dipropylene Glycol, Agar, Hydroxyacetophenone, 1,2-Hexanediol, Potassium Chloride, Polyglyceryl-10 Laurate, Caprylyl Glycol, Sucrose, Butylene Glycol, Adenosine, Ethylhexylglycerin, Pyrus Communis (Pear) Fruit Extract, Rosa Damascena Flower Water, Iris Florentina Root Extract, Cucumis Melo (Melon) Fruit Extract, Hedera Helix (Ivy) Leaf/Stem Extract, Dipotassium Glycyrrhizate, Bifida Ferment Filtrate, Lactobacillus Ferment, Filtrate, Lactobacillus Ferment, Tocopherol",
    "benefits": "Pore tightening, improves skin elasticity, deep hydration, strengthens skin barrier, hypoallergenic",
    "usage_instructions": "Apply the mask at the end of your skincare routine. Leave it on for 3-4 hours or overnight until it becomes transparent. Remove the mask the next morning.",
    "is_featured": True
},
 {
        "name": "Drunk Elephant C-Firma™ Fresh Day Serum",
        "brand": "Drunk Elephant",
        "category": "skincare",
        "subcategory": "serum",
        "description": "A super-potent vitamin C day serum that helps to firm and brighten the look of skin while improving signs of photodamage and aging. It features a powerful antioxidant complex, essential nutrients, and fruit enzymes.",
        "price": 21.99,
        "amazon_url": "https://amzn.to/452mng9",
        "image_url": "https://m.media-amazon.com/images/I/61P6v+1NsEL._SL1500_.jpg",
        "rating": 4.6,
        "review_count": 2100,
        "ingredients": "L-Ascorbic Acid, Ferulic Acid, Vitamin E, Pumpkin Ferment and Pomegranate Extract, Chronocyclin, Grape Juice Extract, Indian Gooseberry",
        "benefits": "Firms and brightens skin, reduces the appearance of fine lines and wrinkles, protects against environmental stressors, improves signs of photodamage.",
        "usage_instructions": "In the morning, apply evenly to clean, dry face, neck, and chest. Follow with a moisturizer and sunscreen.",
        "is_featured": False
    },
    {
        "name": "Tatcha The Water Cream",
        "brand": "Tatcha",
        "category": "skincare",
        "subcategory": "moisturizer",
        "description": "An oil-free, anti-aging water cream that releases a burst of refreshing hydration, leaving skin feeling firm, soft, and healthy. It contains Japanese wild rose to visibly tighten pores and Japanese leopard lily to help control excess oil.",
        "price": 23.00,
        "amazon_url": "https://amzn.to/3UGzAF9",
        "image_url": "https://m.media-amazon.com/images/I/71-BQKj9+wL._SL1500_.jpg",
        "rating": 4.8,
        "review_count": 12500,
        "ingredients": "Japanese Wild Rose, Japanese Leopard Lily, Hadasei-3 (Green Tea, Rice, and Algae), 23-Karat Gold",
        "benefits": "Provides intense hydration, minimizes pores, controls excess oil, and leaves skin with a soft, matte finish.",
        "usage_instructions": "Apply a pearl-sized amount to the face and neck. Can be used morning and night.",
        "is_featured": True
    },
 {
        "name": "Chanel N°5 Eau de Parfum",
        "brand": "Chanel",
        "category": "fragrance",
        "subcategory": "eau de parfum",
        "description": "The quintessential floral bouquet fragrance. A timeless, legendary scent, it is a complex blend of aldehydes, jasmine, rose, and ylang-ylang.",
        "price": 36.50,
        "amazon_url": "https://amzn.to/40Li2vk",
        "image_url": "https://m.media-amazon.com/images/I/71DNQEfCz1L._SL1500_.jpg",
        "rating": 4.8,
        "review_count": 8900,
        "ingredients": "Aldehydes, Jasmine, Rose, Neroli, Ylang-Ylang, Sandalwood, Vetiver",
        "benefits": "An iconic, long-lasting fragrance that is both timeless and elegant.",
        "usage_instructions": "Spray onto pulse points, such as wrists and neck, or lightly mist all over the body.",
        "is_featured": True
    },
    {
        "name": "Dior Sauvage Elixir",
        "brand": "Dior",
        "category": "fragrance",
        "subcategory": "elixir",
        "description": "An exceptionally concentrated fragrance steeped in the emblematic freshness of Sauvage with a spirited heart of spices, a 'bespoke' lavender essence and a blend of rich woods.",
        "price": 118.00,
        "amazon_url": "https://amzn.to/4fsQcKo",
        "image_url": "https://m.media-amazon.com/images/I/51Mn+7xALZL._SL1024_.jpg",
        "rating": 4.7,
        "review_count": 6800,
        "ingredients": "Grapefruit, Spices, Lavender, Sandalwood, Amber",
        "benefits": "Intense and long-lasting scent, with a unique blend of fresh and warm notes. ",
        "usage_instructions": "Spray onto pulse points, such as wrists and neck.",
        "is_featured": False
    },
    {
        "name": "NARS Radiant Creamy Concealer",
        "brand": "NARS",
        "category": "makeup",
        "subcategory": "concealer",
        "description": "An award-winning, multi-purpose concealer that brightens, corrects, and perfects with full, natural-looking coverage. It's enriched with hydrating, multi-action skincare benefits.",
        "price": 25.67,
        "amazon_url": "https://amzn.to/40MWcHG",
        "image_url": "https://m.media-amazon.com/images/I/61oxs+8JJ7L._SL1500_.jpg",
        "rating": 4.7,
        "review_count": 15000,
        "ingredients": "Magnolia Bark Extract, Grape Seed Extract, Vitamin E",
        "benefits": "Corrects imperfections, hydrates skin, and provides a long-wearing, crease-resistant finish.",
        "usage_instructions": "Apply with the applicator directly to the skin to conceal and blend with fingertips, a brush, or a sponge.",
        "is_featured": True
    },
    {
        "name": "Pat McGrath Labs Mothership V: Bronze Seduction Palette",
        "brand": "Pat McGrath Labs",
        "category": "makeup",
        "subcategory": "eyeshadow",
        "description": "An iconic eyeshadow palette with a range of metallic, matte, and shimmering shades. It features creamy, blendable, and highly pigmented formulas for endless looks.",
        "price": 92.00,
        "amazon_url": "https://amzn.to/41pb7Ia",
        "image_url": "https://m.media-amazon.com/images/I/51tOZ91bfdL.jpg",
        "rating": 4.9,
        "review_count": 3500,
        "ingredients": "Talc, Mica, Calcium Sodium Borosilicate, Synthetic Fluorphlogopite, Phenyl Trimethicone",
        "benefits": "Rich pigment, long-lasting wear, and a variety of textures for versatile eye looks.",
        "usage_instructions": "Use a brush or fingertips to apply and blend the shades on the eyelids.",
        "is_featured": True
    },
   
    {
        "name": "Dr. Barbara Sturm Hyaluronic Serum",
        "brand": "Dr. Barbara Sturm",
        "category": "skincare",
        "subcategory": "serum",
        "description": "A powerful hydrating serum that deeply penetrates the skin, providing immediate and long-term hydration. It is formulated with a combination of low and high molecular weight hyaluronic acid.",
        "price": 278.00,
        "amazon_url": "https://amzn.to/4fjlljf",
        "image_url": "https://m.media-amazon.com/images/I/51xl-92XHzL._AC_SL1500_.jpg",
        "rating": 4.5,
        "review_count": 2100,
        "ingredients": "Hyaluronic Acid (low and high molecular weight)",
        "benefits": "Intense hydration, plumps the skin, reduces the appearance of fine lines, and soothes irritation.",
        "usage_instructions": "Dispense a full pipette in the palm of your hand and apply to the face. Gently pat in until fully absorbed.",
        "is_featured": False
    },
    {
        "name": "Guerlain Orchidée Impériale The Cream",
        "brand": "Guerlain",
        "category": "skincare",
        "subcategory": "moisturizer",
        "description": "An exceptional complete care cream that fights all signs of aging. It is enriched with a powerful longevity complex from the orchid flower, visibly reducing wrinkles and improving firmness and radiance.",
        "price": 272.00,
        "amazon_url": "https://amzn.to/4m3dEAgM",
        "image_url": "https://m.media-amazon.com/images/I/51iRLK2nB+L._SL1088_.jpg",
        "rating": 4.9,
        "review_count": 1700,
        "ingredients": "Orchid extracts, Cell Respiration Technology",
        "benefits": "Reduces wrinkles, firms skin, restores radiance, and protects against environmental damage.",
        "usage_instructions": "Apply morning and night to the face and neck using circular motions.",
        "is_featured": False
    },
    {
        "name": "Westman Atelier Face Trace Contour Stick",
        "brand": "Westman Atelier",
        "category": "makeup",
        "subcategory": "contour",
        "description": "A creamy, clean contour stick that adds subtle definition and lift to cheekbones. The blendable, buildable formula is made with Jojoba Oil to nourish the skin.",
        "price": 40.00,
        "amazon_url": "https://amzn.to/3IVu1jH",
        "image_url": "https://m.media-amazon.com/images/I/61c9ecPMMgL._SL1500_.jpg",
        "rating": 4.7,
        "review_count": 810,
        "ingredients": "Jojoba Seed Oil, Raspberry Leaf Stem Cell Extract, Kaolin Clay, Vitamin C & E",
        "benefits": "Provides natural-looking definition, blends seamlessly, and is formulated with nourishing ingredients.",
        "usage_instructions": "Sweep under the cheekbone and blend upward and outward with fingers or a brush. Can also be applied to the sides of the nose and jawline.",
        "is_featured": False
    },
    {
        "name": "Byredo Mojave Ghost Eau de Parfum",
        "brand": "Byredo",
        "category": "fragrance",
        "subcategory": "eau de parfum",
        "description": "An ode to the raw beauty of the Mojave Desert. The scent is a woody, aromatic composition inspired by the ghost flower that blossoms in the vast, arid landscape.",
        "price": 13.99,
        "amazon_url": "https://amzn.to/3Jfjm3m",
        "image_url": "https://m.media-amazon.com/images/I/61yLq5PpIrL._SL1500_.jpg",
        "rating": 4.5,
        "review_count": 950,
        "ingredients": "Ambrette, Magnolia, Sandalwood, Violet, Cedarwood, Vetiver",
        "benefits": "A unique, sophisticated, and long-lasting fragrance with a woody and floral scent profile.",
        "usage_instructions": "Spray on pulse points, such as the neck and wrists.",
        "is_featured": False
    },
    {
        "name": "Men's Gulongtoilette perfume",
        "brand": "WHKDFV",
        "category": "fragrance",
        "subcategory": "eau de parfum",
        "description": "citrus fresh and lasting spray perfume lemon pepper base note cedar 50ml portablemens.",
        "price": 13.99,
        "amazon_url": "https://amzn.to/4l8I7eQ",
        "image_url": "https://m.media-amazon.com/images/I/71qZkzYZkRL._SL1500_.jpg",
        "rating": 4.6,
        "review_count": 196,
        "ingredients": "Amber Wood, Lemon, Mint fresh bergamot flavor, lemon and pepper complement each other to create a delicate and masculine eau de toilette flavormen's cologne",
        "benefits": "Spray on the pulse points behind the wrist, neck, and ears, as well as on clothing for optimal fragrance release.",
        "usage_instructions": "Spray onto pulse points, such as wrists and neck.",
        "is_featured": False
    },
    {
        "name": "Chanel Les Beiges Water-Fresh Tint",
        "brand": "Chanel",
        "category": "makeup",
        "subcategory": "foundation",
        "description": "A light-to-medium coverage foundation with a gel texture and pigmented micro-droplets that create a radiant, healthy-looking glow. It is composed of 75 percent water for a burst of freshness.",
        "price": 28.00,
        "amazon_url": "https://amzn.to/4mo57HV",
        "image_url": "https://m.media-amazon.com/images/I/61QE+rV1OSL._SL1500_.jpg",
        "rating": 4.7,
        "review_count": 634,
        "ingredients": "Water, Tamarind Seed Extract, Mica, Isododecane",
        "benefits": "Provides a fresh, radiant look, delivers a burst of hydration, and evens out skin tone.",
        "usage_instructions": "Dispense the foundation onto the back of your hand, blend the micro-droplets with the included brush, and dab all over the face.",
        "is_featured": False
    },
    {
        "name": "Charlotte Tilbury Airbrush Flawless Foundation",
        "brand": "Charlotte Tilbury",
        "category": "makeup",
        "subcategory": "foundation",
        "description": "A stay-all-day, full-coverage, natural-looking matte foundation that is infused with skincare ingredients to hydrate and protect the skin.",
        "price": 44.99,
        "amazon_url": "https://amzn.to/4ldigT8",
        "image_url": "https://m.media-amazon.com/images/I/51IVOltKGaL._SL1500_.jpg",
        "rating": 4.5,
        "review_count": 8900,
        "ingredients": "Hyaluronic Acid, Airbrush Polymers, Red Clover Extract",
        "benefits": "Provides a smooth, airbrushed finish, reduces the appearance of pores, and is long-wearing.",
        "usage_instructions": "Apply with a brush or sponge from the center of the face outward, blending as you go.",
        "is_featured": False
    },
    {
        "name": "Yves Saint Laurent Lash Clash Extreme Volume Mascara",
        "brand": "Yves Saint Laurent",
        "category": "makeup",
        "subcategory": "mascara",
        "description": "An extreme volume mascara that provides a false-lash effect with high-impact length, lift, and definition. The formula is infused with Iris Florentina extract to protect and condition lashes.",
        "price": 28.00,
        "amazon_url": "https://amzn.to/3Hk8Kj4",
        "image_url": "https://m.media-amazon.com/images/I/51rjD1DyfpL._SL1200_.jpg",
        "rating": 4.2,
        "review_count": 3300,
        "ingredients": "Iris Florentina Extract, Waxes, Polymers",
        "benefits": "Provides extreme volume and length, lifts lashes, and is long-lasting without clumping.",
        "usage_instructions": "Apply from the base of the lashes to the tip in a zigzag motion. Repeat for added volume.",
        "is_featured": False
    },
    {
        "name": "Lancôme Lip Idôle JuicyTreat Lip Oil Gloss",
        "brand": "Lancôme",
        "category": "makeup",
        "subcategory": "lip gloss",
        "description": "A 3D juicy shine oil-in-gloss that juicifies like a gloss and acts like a serum. Supercharged with 20% squalane, this product provides 24H hydration.",
        "price": 14.00,
        "amazon_url": "https://amzn.to/47bqhEE",
        "image_url": "https://m.media-amazon.com/images/I/517-LnVg+FL._SL1500_.jpg",
        "rating": 4.8,
        "review_count": 1882,
        "ingredients": "Squalane, Cherry Oil",
        "benefits": "Provides a glossy shine, hydrates lips, and leaves them feeling smoother and bouncier.",
        "usage_instructions": "Apply to lips using the jumbo applicator for instant shine and hydration.",
        "is_featured": False
    },
    {
        "name": "Givenchy L'Interdit Volumizing & Lengthening Mascara",
        "brand": "Givenchy",
        "category": "makeup",
        "subcategory": "mascara",
        "description": "A volumizing and lengthening mascara that provides a luxurious feel and makes eyelashes look fuller and longer with two coats. The formula is lightweight and non-clumping.",
        "price": 13.00,
        "amazon_url": "https://amzn.to/4oxDz4S",
        "image_url": "https://m.media-amazon.com/images/I/81vMT6mE96L._SL1500_.jpg",
        "rating": 4.1,
        "review_count": 307,
        "ingredients": "Unknown",
        "benefits": "Provides volume and length, feels luxurious, and does not clump.",
        "usage_instructions": "Apply from the base of the lashes to the tip. Can be layered for more dramatic results.",
        "is_featured": False
    },
    {
        "name": "The Ordinary Niacinamide 10% + Zinc 1%",
        "brand": "The Ordinary",
        "category": "skincare",
        "subcategory": "serum",
        "description": "A high-strength vitamin and mineral blemish formula that reduces the appearance of skin blemishes and congestion. The formula also helps to brighten the skin tone and improve overall skin health.",
        "price": 14.99,
        "amazon_url": "https://amzn.to/44ZqIAD",
        "image_url": "https://m.media-amazon.com/images/I/61wAHUgrrtL._SL1500_.jpg",
        "rating": 4.6,
        "review_count": 5000,
        "ingredients": "Aqua (Water), Niacinamide, Pentylene Glycol, Zinc PCA, Dimethyl Isosorbide, Tamarindus Indica Seed Gum, Xanthan Gum, Isoceteth-20, Ethoxydiglycol, Phenoxyethanol, Chlorphenesin.",
        "benefits": "Reduces blemishes, minimizes pores, regulates sebum, and improves skin texture. Suitable for most skin types, particularly oily and acne-prone skin.",
        "usage_instructions": "Apply a few drops to the face in the morning and evening before heavier creams. Avoid use with Vitamin C products.",
        "is_featured": False
    },
    {
        "name": "COSRX Advanced Snail 96 Mucin Power Essence",
        "brand": "COSRX",
        "category": "skincare",
        "subcategory": "essence",
        "description": "An essence formulated with 96% Snail Secretion Filtrate, known for its powerful hydrating and healing properties. It helps to repair skin, reduce fine lines, and improve skin vitality.",
        "price": 34.99,
        "amazon_url": "https://amzn.to/3UbzcOR",
        "image_url": "https://m.media-amazon.com/images/I/71CEjwLxS1L._SL1500_.jpg",
        "rating": 4.7,
        "review_count": 8500,
        "ingredients": "Snail Secretion Filtrate, Betaine, Butylene Glycol, 1,2-Hexanediol, Sodium Hyaluronate, Panthenol, Arginine, Allantoin, Carbomer, Phenoxyethanol.",
        "benefits": "Deeply moisturizes, repairs damaged skin, soothes irritation, and reduces hyperpigmentation. A must-have for dry, sensitive, or damaged skin.",
        "usage_instructions": "After cleansing and toning, apply a small amount to your entire face. Gently pat with fingertips to aid absorption.",
        "is_featured": False
    },
    {
        "name": "Huda Beauty #FauxFilter Luminous Matte Concealer",
        "brand": "Huda Beauty",
        "category": "makeup",
        "subcategory": "concealer",
        "description": "A creamy, full-coverage, yet lightweight concealer that brightens the under-eye area and conceals blemishes. It provides a long-lasting, luminous matte finish without creasing or settling into fine lines.",
        "price": 30.00,
        "amazon_url": "https://amzn.to/4l90sIE",
        "image_url": "https://m.media-amazon.com/images/I/51nx9-jYLuL._SL1500_.jpg",
        "rating": 4.4,
        "review_count": 2500,
        "ingredients": "Water, Cyclopentasiloxane, Talc, Cetyl PEG/PPG-10/1 Dimethicone, Phenyl Trimethicone, Glycerin, Propylene Glycol, Caprylic/Capric Triglyceride, Dimethicone.",
        "benefits": "Full coverage, long-wearing, non-creasing, and brightening. Perfect for correcting skin imperfections and highlighting.",
        "usage_instructions": "Apply directly to the desired area and blend with a beauty sponge, brush, or fingertips.",
        "is_featured": True
    },
    {
        "name": "NARS Orgasm Blush",
        "brand": "NARS",
        "category": "makeup",
        "subcategory": "blush",
        "description": "A cult-favorite powder blush in the iconic peachy-pink shade with a golden shimmer. This universally flattering blush provides a natural, healthy-looking flush and a radiant glow.",
        "price": 27.00,
        "amazon_url": "https://amzn.to/4lec0ud",
        "image_url": "https://m.media-amazon.com/images/I/61zZLWek1WL._SL1500_.jpg",
        "rating": 4.8,
        "review_count": 12000,
        "ingredients": "Talc, Zinc Stearate, Octyldodecyl Stearoyl Stearate, Octyldodecyl Stearate, Phenoxyethanol, Caprylyl Glycol.",
        "benefits": "Provides a natural-looking color with a touch of golden shimmer. Buildable and long-lasting formula that is suitable for all skin tones.",
        "usage_instructions": "Sweep the brush across the powder and tap off excess. Apply to the apples of the cheeks and blend outward.",
        "is_featured": False
    },
    {
        "name": "Tom Ford Oud Wood Eau de Parfum",
        "brand": "Tom Ford",
        "category": "fragrance",
        "subcategory": "eau de parfum",
        "description": "A rare, exotic, and distinctive fragrance featuring a blend of rare oud wood, sandalwood, and vetiver. It is a smoky, woody scent that is both sophisticated and sensual.",
        "price": 331.27,
        "amazon_url": "https://amzn.to/4503Jp3",
        "image_url": "https://m.media-amazon.com/images/I/710+ntilt5L._SL1500_.jpg",
        "rating": 4.6,
        "review_count": 3000,
        "ingredients": "Alcohol Denat., Water, Fragrance, Linalool, Limonene, Coumarin, Eugenol, Geraniol.",
        "benefits": "A luxurious and long-lasting scent with a complex and captivating blend of woody and spicy notes. Perfect for special occasions or daily wear.",
        "usage_instructions": "Spray on pulse points, such as the neck and wrists.",
        "is_featured": True
    },
    {
        "name": "Lattafa Yara for Women Eau de Parfum",
        "brand": "Lattafa",
        "category": "fragrance",
        "subcategory": "eau de parfum",
        "description": "A popular and affordable fragrance for women with a sweet and enchanting scent profile. It combines notes of tangerine, heliotrope, orchid, and vanilla, creating a long-lasting and appealing aroma.",
        "price": 25.00,
        "amazon_url": "https://amzn.to/4m578Js",
        "image_url": "https://m.media-amazon.com/images/I/41LruIHspoL._SL1000_.jpg",
        "rating": 4.5,
        "review_count": 1500,
        "ingredients": "Alcohol Denat., Water, Fragrance, Limonene, Linalool, Citral, Geraniol.",
        "benefits": "An affordable yet high-quality fragrance with a long-lasting sweet and floral scent. A great option for everyday use.",
        "usage_instructions": "Spray on pulse points, such as the neck and wrists.",
        "is_featured": False
    },
        
    {
        "name": "Luxurious Hydrating Skincare Gift Set with Cordyceps Extract",
        "brand": "MEIYUANNAISI",
        "category": "Skincare",
        "subcategory": "Set",
        "description": "A curated collection of our most popular skincare essentials.",
        "price": 31.99,
        "amazon_url": "https://amzn.to/45hadyR",
        "image_url": "https://m.media-amazon.com/images/I/71xiwq-6QUL._SL1500_.jpg",
        "rating": 4.9,
        "review_count": 350,
        "ingredients": "snow lotus extract, ginseng extract",
        "benefits": "Complete skincare routine in one box.",
        "usage_instructions": "Follow instructions on individual product packaging.",
        "is_featured": True,
        
    },
    {
        "name": "Hydrating Rose Mist",
        "brand": "Flora & Co",
        "category": "Skincare",
        "subcategory": "Toner",
        "description": "A refreshing mist to hydrate and soothe your skin.",
        "price": 9.88,
        "amazon_url": "https://amzn.to/3UJP1MU",
        "image_url": "https://m.media-amazon.com/images/I/61gWzGbEirL._SL1500_.jpg",
        "rating": 4.7,
        "review_count": 120,
        "ingredients": "Rose water, Aloe vera, Glycerin",
        "benefits": "Hydrates, soothes, and preps skin.",
        "usage_instructions": "Spray on face after cleansing or throughout the day.",
        "is_featured": False,
        
    },
    {
        "name": "Milani Color Fetish Matte Lipstick (Sensual)",
        "brand": "Milani",
        "category": "Makeup",
        "subcategory": "Lipstick",
        "description": "Long-lasting, non-drying matte lipstick in a luxurious velvet finish.",
        "price": 8.97,
        "amazon_url": "https://amzn.to/46YGAoz",
        "image_url": "https://m.media-amazon.com/images/I/51vEl2dLKOL._SL1500_.jpg",
        "rating": 4.5,
        "review_count": 210,
        "ingredients": "Dimethicone, Jojoba oil, Vitamin E",
        "benefits": "Rich color, comfortable wear, long-lasting.",
        "usage_instructions": "Apply directly to lips from the bullet or with a brush.",
        "is_featured": True,
      
    },
    {
        "name": "Satin Silk Foundation",
        "brand": "Dermacol",
        "category": "Makeup",
        "subcategory": "Foundation",
        "description": "A lightweight foundation that provides a luminous, satin finish.",
        "price": 17.49,
        "amazon_url": "https://amzn.to/4fgIYsA",
        "image_url": "https://m.media-amazon.com/images/I/615S5oXqxVL._SL1500_.jpg",
        "rating": 4.6,
        "review_count": 400,
        "ingredients": "Hyaluronic acid, SPF 30",
        "benefits": "Evens skin tone, protects from sun, radiant finish.",
        "usage_instructions": "Apply with a sponge or brush and blend well.",
        "is_featured": True,
        
    },
    {
        "name": "Mandarinsky Limited Edition by Armaf for Men - 3.4 oz EDP Spray",
        "brand": "odssey",
        "category": "Fragrance",
        "subcategory": "Perfume",
        "description": "A vibrant and energizing mandarin-based scent,Blends zesty citrus with warm woody undertones",
        "price": 31.00,
        "amazon_url": "https://amzn.to/4fmeUvU",
        "image_url": "https://m.media-amazon.com/images/I/51ESxlJXKQL._SL1290_.jpg",
        "rating": 4.9,
        "review_count": 95,
        "ingredients": "Alcohol, Fragrance oil, Sandalwood extract, Vetiver oil",
        "benefits": "Sophisticated, elegant, and long-lasting aroma.",
        "usage_instructions": "Spray on pulse points for a lasting fragrance.",
        "is_featured": True,
      
    }
    ]


    for product_data in products:
        existing_product = Product.query.filter_by(name=product_data['name']).first()
        if not existing_product:
            new_product = Product(
                name=product_data['name'],
                brand=product_data['brand'],
                category=product_data['category'],
                subcategory=product_data['subcategory'],
                description=product_data['description'],
                price=product_data['price'],
                amazon_url=product_data['amazon_url'],
                image_url=product_data['image_url'],
                rating=product_data['rating'],
                review_count=product_data['review_count'],
                ingredients=product_data['ingredients'],
                benefits=product_data['benefits'],
                usage_instructions=product_data['usage_instructions'],
                is_featured=product_data['is_featured']
            )
            db.session.add(new_product)

    db.session.commit()
    print(f"Seeded {len(products)} products.")